language: scala
script:
    - sbt ++$TRAVIS_SCALA_VERSION clean compile test "project benchmark" clean compile test publishLocal 
scala:
  - 2.11.4
jdk:
  - oraclejdk7
notifications:
  email:
    - mail@martin-senne.de
    - marvin.hansen@gmail.com
